### ISSUE TITLE
Confusing API

### ISSUE THREAD

**Issue by jdf-id-au** [Efferent-Health/HL7-V2#4]
Thanks for this library.

[This wiki paragraph](https://github.com/Efferent-Health/HL7-V2/wiki/Documentation#bypass-validation) and ideally inline documentation should make it clearer that `ParseMessage` 's parameter `bypassValidation` must be `true` if working with a `new Message()` (to which segments are manually added individually). The same concept applies to `SerializeMessage`'s parameter `validate` needing to be `false`.

**Comment by jaime-olivares** [comment]
Several hints has been provided in both the wiki and inline code.
