### ISSUE TITLE
Message serialization issue

### ISSUE THREAD

**Issue by EricBeardIRC** [Efferent-Health/HL7-V2#5]
Serializing a message doesn't use the encoding that was assigned to the segment.  It generates a new default HL7Encoding class and uses that instead.  I've got a fix with test cases.  Not sure how to get that into the project.

**Comment by jaime-olivares** [comment]
Hi Eric,
You have to create a pull request with the fix, and also add the unit tests (positive and negative) in the corresponding project.

**Comment by EricBeardIRC** [comment]
When I try to push my branch upstream I'm getting a 403 error.  Never pushed to public github before, so I may be missing some configuration.

**Comment by jaime-olivares** [comment]
Did you create your own fork and pushed your branch there?

Sent from my iPhone 14
________________________________

**Comment by EricBeardIRC** [comment]
I did not.  Let me do that.

**Comment by EricBeardIRC** [comment]
OK - I think I figured it out.  I believe the PR should be there now.

BTW.  TY for this library.  It's been a great help.

**Comment by jaime-olivares** [comment]
I can see your PR #6 

However, there are several mishaps in your sample test:
- Every message should have a header (MSH) without exceptions
- You can customize the character encoding for the entire message (MSH.2), which applies to all segements, according to the standard.
- **All segments should have the same encoding**, the same attached to the message
- When serializing a message, the encoding specified in MSH.2 is used

What you are trying to accomplish is out of the HL7 standard, and therefore, not supported.

**Comment by EricBeardIRC** [comment]
I'm willing to accept that many HL7 messages need an MSH.2 segment, however not all do.  There are major health insurance companies that do not require them in their transactions.  In those cases, I need a mechanism to change the delimiter.  The code as it stands doesn't look at or for an MSH segment to determine the delimiter to use.  Another fix would be to optionally pass in an encoding to use and apply that to all segments so the same delimiter was used.

**Comment by jaime-olivares** [comment]
During the serialization of an HL7 message, the encoding is taken from the message's Encoding property, not from individual segments.
So my suggestion is the following:
- Create a new message
- **Create a unique HL7Encoding object**
- Assign it to the message
- Use it when creating every segment or field
- Finally serialize your message -- it will use the Message's encoding

**Comment by EricBeardIRC** [comment]
That works.  TY.  Solves the problem for these oddball HL7 folks.  Appreciate your assistance.
